import type { Language } from '../types'

const SK_CAPITAL_NAMES: Record<string, string> = {
  'Abu Dhabi': 'Abú Zabí',
  'Addis Ababa': 'Addis Abeba',
  Algiers: 'Alžír',
  Amman: 'Ammán',
  Amsterdam: 'Amsterdam',
  'Andorra la Vella': 'Andorra la Vella',
  Ankara: 'Ankara',
  Antananarivo: 'Antananarivo',
  Apia: 'Apia',
  Ashgabat: 'Ašchabad',
  Asmara: 'Asmara',
  Astana: 'Astana',
  Asunción: 'Asunción',
  Athens: 'Atény',
  Baghdad: 'Bagdad',
  Baku: 'Baku',
  Bamako: 'Bamako',
  Bangkok: 'Bangkok',
  Bangui: 'Bangui',
  Beijing: 'Peking',
  Beirut: 'Bejrút',
  Belgrade: 'Belehrad',
  Berlin: 'Berlín',
  Bern: 'Bern',
  Bishkek: 'Biškek',
  Brazzaville: 'Brazzaville',
  Brussels: 'Brusel',
  Bucharest: 'Bukurešť',
  Budapest: 'Budapešť',
  Cairo: 'Káhira',
  Chișinău: 'Kišiňov',
  Copenhagen: 'Kodaň',
  Damascus: 'Damask',
  Dublin: 'Dublin',
  Dushanbe: 'Dušanbe',
  Geneva: 'Ženeva',
  'Guatemala City': 'Guatemala',
  Hanoi: 'Hanoj',
  Havana: 'Havana',
  Helsinki: 'Helsinki',
  Jerusalem: 'Jeruzalem',
  Kyiv: 'Kyjev',
  Lisbon: 'Lisabon',
  Ljubljana: 'Ľubľana',
  London: 'Londýn',
  Luxembourg: 'Luxemburg',
  Madrid: 'Madrid',
  Minsk: 'Minsk',
  Moscow: 'Moskva',
  Nicosia: 'Nikózia',
  'North Nicosia': 'Severná Nikózia',
  Oslo: 'Oslo',
  Paris: 'Paríž',
  Prague: 'Praha',
  Pristina: 'Priština',
  Reykjavik: 'Reykjavík',
  Riga: 'Riga',
  Rome: 'Rím',
  Seoul: 'Soul',
  Skopje: 'Skopje',
  Sofia: 'Sofia',
  Stockholm: 'Štokholm',
  Tallinn: 'Tallinn',
  Tehran: 'Teherán',
  Tirana: 'Tirana',
  Tokyo: 'Tokio',
  Tunis: 'Tunis',
  Vienna: 'Viedeň',
  Vilnius: 'Vilnius',
  Warsaw: 'Varšava',
  Yerevan: 'Jerevan',
  Zagreb: 'Záhreb',
}

export function getCapitalDisplayName(capital: string, language: Language): string {
  if (language !== 'sk') return capital
  return SK_CAPITAL_NAMES[capital] ?? capital
}
